baseURL = 'https://example.org/'
title = 'Pham Minh Kha Blog'

# Theme configuration
theme = 'DoIt'

# Enable features
enableRobotsTXT = true
enableEmoji = true

# Default language
defaultContentLanguage = 'vi'
defaultContentLanguageInSubdir = false

# Language configuration
[languages]
  [languages.vi]
    languageCode = 'vi'
    languageName = 'Tiếng Việt'
    weight = 1
    title = 'Blog của Phạm Minh Kha'
    [languages.vi.params]
      description = 'Blog chia sẻ kiến thức về Java, Programming và Technology'
  
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    title = 'Pham Minh Kha Blog'
    [languages.en.params]
      description = 'Blog about Java, Programming and Technology'

# Menu configuration cho tiếng Việt
[languages.vi.menu]
  [[languages.vi.menu.main]]
    identifier = "home"
    name = "Trang chủ"
    url = "/"
    weight = 0
  [[languages.vi.menu.main]]
    identifier = "posts"
    name = "Bài viết"
    url = "/posts/"
    weight = 1
  [[languages.vi.menu.main]]
    identifier = "tags"
    name = "Thẻ"
    url = "/tags/"
    weight = 2
  [[languages.vi.menu.main]]
    identifier = "categories"
    name = "Danh mục"
    url = "/categories/"
    weight = 3
  [[languages.vi.menu.main]]
    identifier = "about"
    name = "Giới thiệu"
    url = "/about/"
    weight = 4

# Menu configuration cho tiếng Anh
[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "home"
    name = "Home"
    url = "/en/"
    weight = 0
  [[languages.en.menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/en/posts/"
    weight = 1
  [[languages.en.menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/en/tags/"
    weight = 2
  [[languages.en.menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/en/categories/"
    weight = 3
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/en/about/"
    weight = 4

# Params configuration
[params]
  # DoIt theme version
  version = "0.3.X"
  # site description
  description = "My Blog Site"
  # Ignore some log messages
  ignoreLogs = ['warning-goldmark-raw-html', 'shortcode-not-found']
  # site keywords
  keywords = ["Blog", "Hugo", "DoIt"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # Author config
  [params.author]
    name = "Phạm Minh Kha"
    email = "phamminhkha19091710@gmail.com"
    link = "https://github.com/PhamMinhKha0710"
  # Home page profile
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.png"
    # title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page (HTML format is supported)
    subtitle = "Welcome to my blog"
    # whether to use typeit animation for subtitle
    typeit = true
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
    
  # Page config
  [params.page]
    # TOC config
    [params.page.toc]
      # whether to enable the table of contents
      enable = true
      # whether to keep the static table of contents expanded
      keepStatic = false
      # whether to make the table of contents in the sidebar automatically collapsed
      auto = true
    
    # Mermaid diagram support
    [params.page.mermaid]
      enable = true
      # Mermaid theme: "default", "dark", "forest", "neutral"
      theme = "default"

# Markup configuration to allow raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Suppress raw HTML warnings
ignoreLogs = ['warning-goldmark-raw-html']